package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gobot/internal/commands"
	"gobot/internal/commands/filter"
	"gobot/internal/commands/giveaway"
	"gobot/internal/commands/juicewrld"
	"gobot/internal/commands/lastfm"
	"gobot/internal/commands/leveling"
	"gobot/internal/commands/moderation"
	"gobot/internal/commands/radio"
	"gobot/internal/commands/ripper"
	"gobot/internal/commands/utility"
	"gobot/internal/commands/voice"

	"github.com/bwmarrin/discordgo"
)

const (
	defaultPrefix = ","
	subcmdPrefix  = "> "
)

type catStats struct {
	baseCount  int
	totalCount int
}

var permList = []struct {
	Bit  int64
	Name string
}{
	{discordgo.PermissionAdministrator, "Administrator"},
	{discordgo.PermissionManageGuild, "Manage Server"},
	{discordgo.PermissionManageRoles, "Manage Roles"},
	{discordgo.PermissionManageChannels, "Manage Channels"},
	{discordgo.PermissionManageMessages, "Manage Messages"},
	{discordgo.PermissionManageNicknames, "Manage Nicknames"},
	{discordgo.PermissionChangeNickname, "Change Nickname"},
	{discordgo.PermissionBanMembers, "Ban Members"},
	{discordgo.PermissionKickMembers, "Kick Members"},
	{discordgo.PermissionModerateMembers, "Moderate Members"},
	{discordgo.PermissionManageGuildExpressions, "Manage Expressions"},
	{discordgo.PermissionVoiceMoveMembers, "Move Members"},
	{discordgo.PermissionVoiceMuteMembers, "Mute Members"},
	{discordgo.PermissionVoiceDeafenMembers, "Deafen Members"},
}

func main() {
	registry := commands.NewRegistry()
	if err := registry.RegisterAll(
		utility.Commands,
		moderation.Commands,
		filter.Commands,
		juicewrld.Commands,
		lastfm.Commands,
		ripper.Commands,
		radio.Commands,
		voice.Commands,
		leveling.Commands,
		giveaway.Commands,
	); err != nil {
		fmt.Fprintf(os.Stderr, "registry error: %v\n", err)
		os.Exit(1)
	}

	allCmds := registry.AllCommands()
	categoryMap := make(map[string][]commands.Command)
	for _, cmd := range allCmds {
		cat := cmd.Category()
		if cat == "" {
			cat = "Utility"
		}
		categoryMap[cat] = append(categoryMap[cat], cmd)
	}

	categories := make([]string, 0, len(categoryMap))
	for cat := range categoryMap {
		categories = append(categories, cat)
	}
	sort.Strings(categories)

	globalBase := 0
	globalTotal := 0
	statsMap := make(map[string]catStats)

	for cat, cmds := range categoryMap {
		base := len(cmds)
		subs := 0
		for _, cmd := range cmds {
			if subProvider, ok := cmd.(commands.Subcommandable); ok {
				subs += len(subProvider.Subcommands())
			}
		}
		total := base + subs
		statsMap[cat] = catStats{baseCount: base, totalCount: total}
		globalBase += base
		globalTotal += total
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Commands - %d (%d Total)\n\n", globalBase, globalTotal))
	sb.WriteString("> prefix: `,`\n>\n")
	sb.WriteString("> `<required>` - `[optional]` - `> ` = subcmd\n>\n")
	sb.WriteString("> *Auto-generated by `go generate`* **do not edit manually.**\n\n")
	sb.WriteString("> **Some permissions may be missing.**\n\n")

	sb.WriteString("**Categories:** ")
	navLinks := make([]string, 0, len(categories))
	for _, cat := range categories {
		st := statsMap[cat]
		navLinks = append(navLinks, fmt.Sprintf("[%s](#%s) (%d)", cat, anchorSlug(cat), st.totalCount))
	}
	sb.WriteString(strings.Join(navLinks, " · ") + "\n\n")

	for _, cat := range categories {
		cmds := categoryMap[cat]
		sort.Slice(cmds, func(i, j int) bool {
			return cmds[i].Name() < cmds[j].Name()
		})

		st := statsMap[cat]
		sb.WriteString("---\n\n")
		sb.WriteString(fmt.Sprintf("## %s - %d (%d Total)\n\n", cat, st.baseCount, st.totalCount))
		sb.WriteString("| Command | Aliases | Usage | Description | Permission |\n")
		sb.WriteString("|---|---|---|---|---|\n")

		for _, cmd := range cmds {
			prefix := defaultPrefix
			if _, ok := cmd.(commands.SlashOnly); ok {
				prefix = "/"
			}

			name := esc(cmd.Name())

			aliases := "-"
			if a := cmd.Aliases(); len(a) > 0 {
				formatted := make([]string, len(a))
				for i, alias := range a {
					formatted[i] = "`" + esc(alias) + "`"
				}
				aliases = strings.Join(formatted, ", ")
			}

			usage := fmt.Sprintf("`%s%s`", prefix, cmd.Name())
			if u := strings.TrimSpace(cmd.Usage()); u != "" {
				usage = fmt.Sprintf("`%s%s %s`", prefix, cmd.Name(), esc(u))
			}

			desc := esc(cmd.Description())
			if desc == "" {
				desc = "-"
			}

			perm := permLabel(cmd)

			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n", name, aliases, usage, desc, perm))

			if subProvider, ok := cmd.(commands.Subcommandable); ok {
				subcommands := append([]commands.Subcommand(nil), subProvider.Subcommands()...)
				sort.Slice(subcommands, func(i, j int) bool {
					return subcommands[i].Name < subcommands[j].Name
				})

				for _, sub := range subcommands {
					subUsage := fmt.Sprintf("`%s%s %s`", prefix, cmd.Name(), esc(sub.Name))
					if u := strings.TrimSpace(sub.Usage); u != "" {
						subUsage = fmt.Sprintf("`%s%s %s %s`", prefix, cmd.Name(), esc(sub.Name), esc(u))
					}
					subDesc := esc(sub.Description)
					if subDesc == "" {
						subDesc = "-"
					}
					sb.WriteString(fmt.Sprintf("| %s`%s` | - | %s | %s | - |\n", subcmdPrefix, esc(sub.Name), subUsage, subDesc))
				}
			}
		}

		sb.WriteString("\n")
	}

	outDir := "docs"
	outFile := filepath.Join(outDir, "COMMANDS.md")

	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "directory error: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("%s generated\n", outFile)
}

func esc(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

func anchorSlug(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == ' ' {
			if r == ' ' {
				b.WriteRune('-')
			} else {
				b.WriteRune(r)
			}
		}
	}
	return b.String()
}

func permLabel(cmd commands.Command) string {
	pc, ok := cmd.(commands.PermissionChecker)
	if !ok {
		return "-"
	}
	p := pc.Permissions()
	if p == 0 {
		return "-"
	}
	for _, perm := range permList {
		if p&perm.Bit != 0 {
			return perm.Name
		}
	}
	return fmt.Sprintf("`0x%X`", p)
}
